spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.sql: debug
